# -*- coding: utf-8 -*-
"""Cópia de Projeto Final | Análise Exploratória de Dados sobre Hábitos de Saúde e Bem-Estar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xWoQ872Iib1ES4fqPVipTE279x1MloZZ

## Análise Exploratória de Dados sobre Hábitos de Saúde e Bem-Estar

**Objetivo do Projeto**

O objetivo é realizar uma análise exploratória de dados sobre hábitos de saúde e bem-estar coletados por meio de um questionário.

A pesquisa foi realizada em outubro de 2025.

**Perguntas de Pesquisa**
* Qual é a frequência de atividade física entre os participantes?
* Qual é o consumo de frutas e bebidas açucaradas semanalmente?
* Existe uma relação entre a prática de atividade física e o consumo de alimentos saudáveis?
* Como variam os padrões de sono e o tempo de tela entre os participantes?
"""

import pandas as pd

dados = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vResfZtKfATsuGT-EgsyFoPaezv8XxIBx_PRpQRd-U3-uyIG2bQzA_-zmp9QEUhz2S6361yOTzsf6h9/pub?gid=373547015&single=true&output=csv")

dados

dados.hist()

dados["Quantos dias por semana você pratica atividades físicas?"].hist()

dados["Quantas porções de frutas você consome em uma semana?"].hist()

"""### Resumo do histograma

* A maioria dos participantes pratica atividade física entre 0 e 1 vez por semana. Isso pode ser visto pela alta frequência de respostas próximas a esses valores.
* Poucos participantes praticam atividade física de maneira mais intensa (de 4 a 7 vezes por semana), sugerindo que uma prática regular de exercícios ainda não é comum entre os respondentes.
* Essa distribuição é muito concentrada em valores baixos, o que pode indicar uma tendência de baixa frequência de atividade física na amostra.
"""

dados["Quantas horas de sono você costuma ter em uma noite durante a semana?"].value_counts()

dados["Quantas bebidas açucaradas (refrigerantes, sucos de caixinha ou energéticos) você consome em uma semana?"].value_counts()

"""### Resumo

**Consumo de Frutas por Semana**

* **Consumo Baixo de Frutas:** A quantidade mais comum de consumo de frutas entre os participantes é de 1 porção por semana, com 7 pessoas relatando esse valor. Isso indica que, para muitos, o consumo de frutas é baixo.

* **Ausência de Consumo:** Existem 2 participantes que relataram não consumir nenhuma porção de frutas por semana (valor de 0). Esse dado reforça a tendência de consumo baixo ou nulo de frutas para uma parte da amostra.

* **Outliers de Consumo Alto:** Há alguns valores atípicos significativos, como um participante consumindo 40 porções de frutas e outro consumindo 23 porções por semana. Esses valores estão bem acima do consumo médio e podem indicar hábitos alimentares específicos ou escolhas individuais.

**Prática de Atividades Físicas por Semana**

* **Baixa Frequência de Atividade Física:** A maioria dos participantes relatou praticar atividades físicas 1 vez por semana (10 pessoas) ou não praticar atividades físicas (6 pessoas). Esses são os valores mais comuns e indicam que a prática de atividade física regular é limitada na amostra.

* **Atividade Física Regular:** Apenas um participante relatou praticar atividades físicas diariamente (7 vezes por semana), o que representa uma pequena parcela da amostra com um hábito de exercício frequente.

"""

dados.describe()

"""### Destaques

* **Count:** Indica o número total de respostas válidas para cada pergunta (neste caso, 23 para cada coluna).
* **Mean (Média):** Representa a média aritmética dos valores para cada coluna. No caso de "Quantas porções de frutas você consome em uma semana?", a média é de aproximadamente 4,48 porções, o que sugere um consumo moderado. Já a média de 10,39 para bebidas açucaradas indica um consumo elevado em comparação com frutas.
* **Std (Desvio Padrão):** Mede a variabilidade dos dados. Um valor alto de desvio padrão, como 12,61 para bebidas açucaradas e 14,04 para horas de dispositivos móveis, indica que há uma grande variação nas respostas entre os participantes.
* **Min e Max:** Mostram os valores mínimo e máximo para cada coluna. Por exemplo, o consumo de frutas varia de 0 até 40 porções por semana, enquanto o tempo em dispositivos móveis vai de 2 a 50 horas semanais.
"""

media_sono = dados["Quantas horas de sono você costuma ter em uma noite durante a semana?"].mean()
mediana_sono = dados["Quantas horas de sono você costuma ter em uma noite durante a semana?"].median()

print(media_sono)
print(mediana_sono)

media_bebidas = dados["Quantas bebidas açucaradas (refrigerantes, sucos de caixinha ou energéticos) você consome em uma semana?"].mean()
mediana_bebidas = dados["Quantas bebidas açucaradas (refrigerantes, sucos de caixinha ou energéticos) você consome em uma semana?"].median()

print(media_bebidas)
print(mediana_bebidas)

"""### Principais informações

**Horas de Sono por Noite**
* Média: A média de horas de sono entre os participantes é de 6 horas por noite.
* Mediana: A mediana é de 5 horas por noite, o que significa que metade dos participantes dorme até 5 horas ou menos, enquanto a outra metade dorme mais que isso.

**Consumo de Bebidas Açucaradas por Semana**
* Média: O consumo médio de bebidas açucaradas é de aproximadamente 10,39 bebidas por semana.
* Mediana: A mediana é de 5 bebidas por semana, indicando que metade dos participantes consome até 5 bebidas açucaradas por semana, enquanto a outra metade consome mais.
"""